# .github/workflows/documentation.yml
name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@1.0.0-rc.1
        with:
          inputs: "Sources"
          module-name: TableView
          format: html
          output: "docs"
      - name: git status
        run: git status

          

