
name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/documentation.yml
      - Sources/TableView/**.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Swift Doc
        uses: SwiftDocOrg/swift-doc@1.0.0-rc.1
        with:
          module-name: "TableView"
          format: "html"
          output: "docs"

